### ISSUE TITLE
List of new furniture/machines you'd like to see new custom model being made

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Obenseuer-Issues#2623]
This is an expansion of #2412 for requests to add brand new models to the game, made from scratch.

- [ ] Breadbox - a small breadbox player buys or crafts that is a dry storage that slows the spoilage time of breed and breed-alike food to last for 2-3 days
![image](https://github.com/user-attachments/assets/d7ba7926-14ac-40cd-91e6-bb95cb2349e8)

- [ ] Cigarette Rolling Machine - a small manual and/or electric machine that allows to craft shroom rollies (instead of stove) and homemade cigarettes
![image](https://github.com/user-attachments/assets/d87a000b-3f6a-4418-88ee-73ac93aa0f9a)

- [ ] Fridge Barrel - a refrigerated variant of standard fluid barrels, made out of combined blue barrel and fridge models #2451

- [ ] Vintage Drawing Table - a low-tier equivalent of Drawing Table that supports player at early game with no skill and with crude recipes #2471

- [ ] Criss-Crossy Fencing - decorative fencing for players to use #1595

**Comment by l-HealthAngel-l** [comment]
- [ ] Mini fridge, size like dishwasher,preserves food with "Refrigerator" stat and store half amount of huge fridge (16 slots) without freezer.
![minifridge](https://github.com/user-attachments/assets/73784144-53cb-4596-b56a-4707a41465b4)
